[namespace]
default = "rift_commanders"

[env]
account_address = "0x063a29c74fd5992b0e4042dbdd227bf835c555170a11e4bd492703cd6fee3271"
private_key = "0x0525b9e73489073bf665f3381b021c5576e2010bb41ee6f67611e3341d31c9f1"
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"

[world]
seed = "rift_commanders_1"
name = "Rift Commanders"
description = "Become a manager"
cover_uri = "file://assets/cover.png"
website = "https://rift-commanders.vercel.app/"


[writers]
"rift_commanders" = [
    "rift_commanders-lobby",
    "rift_commanders-planning",
    "rift_commanders-execution",
    "rift_commanders-rift"
    ]